'use strict'

export const APPLICATION_STATE_CHANGED = 'APPLICATION_STATE_CHANGED'

export const FACEBOOK_LOGIN_REQUESTED  = 'FACEBOOK_LOGIN_REQUESTED'
export const FACEBOOK_LOGIN_SUCCEEDED  = 'FACEBOOK_LOGIN_SUCCEEDED'
export const FACEBOOK_LOGIN_FAILED     = 'FACEBOOK_LOGIN_FAILED'

export const FACEBOOK_GRAPH_DATA_REQUESTED = 'FACEBOOK_GRAPH_DATA_REQUESTED'
export const FACEBOOK_GRAPH_DATA_SUCCEEDED = 'FACEBOOK_GRAPH_DATA_SUCCEEDED'
export const FACEBOOK_GRAPH_DATA_FAILED    = 'FACEBOOK_GRAPH_DATA_FAILED'

export const SOCKET_CONNECTION_REQUESTED = 'SOCKET_CONNECTION_REQUESTED'
export const SOCKET_CONNECTION_SUCCEEDED = 'SOCKET_CONNECTION_SUCCEEDED'
export const SOCKET_CONNECTION_FAILED    = 'SOCKET_CONNECTION_FAILED'

export const SOCKET_LOGIN_USER_REQUESTED   = 'SOCKET_LOGIN_USER_REQUESTED'
export const SOCKET_QUERY_USER_REQUESTED   = 'SOCKET_QUERY_USER_REQUESTED'
export const SOCKET_QUERY_USER_RECEIVED    = 'SOCKET_QUERY_USER_RECEIVED'
export const SOCKET_QUERY_ROOM_REQUESTED   = 'SOCKET_QUERY_ROOM_REQUESTED'
export const SOCKET_QUERY_ROOM_RECEIVED    = 'SOCKET_QUERY_ROOM_RECEIVED'
export const SOCKET_QUERY_UNKNOWN_RECEIVED = 'SOCKET_QUERY_UNKNOWN_RECEIVED'

export const SOCKET_UPDATE_MATCH_REQUESTED = 'SOCKET_UPDATE_MATCH_REQUESTED'

export const DB_LOAD_USER = 'DB_LOAD_USER'

export const SCENE_NAVIGATION_HOME     = 'SCENE_NAVIGATION_HOME'
export const SCENE_NAVIGATION_CONTACTS = 'SCENE_NAVIGATION_CONTACTS'
export const SCENE_NAVIGATION_CONTACT  = 'SCENE_NAVIGATION_CONTACT'
export const SCENE_NAVIGATION_PROFILE  = 'SCENE_NAVIGATION_PROFILE'
export const SCENE_NAVIGATION_MATCH    = 'SCENE_NAVIGATION_MATCH'
export const SCENE_NAVIGATION_LOGOUT   = 'SCENE_NAVIGATION_LOGOUT'
export const SCENE_NAVIGATION_ERROR    = 'SCENE_NAVIGATION_ERROR'