'use strict'

export const FACEBOOK_LOGIN_REQUESTED  = 'FACEBOOK_LOGIN_REQUESTED'
export const FACEBOOK_LOGIN_SUCCEEDED  = 'FACEBOOK_LOGIN_SUCCEEDED'
export const FACEBOOK_LOGIN_FAILED     = 'FACEBOOK_LOGIN_FAILED'
export const FACEBOOK_LOGOUT           = 'FACEBOOK_LOGOUT'

export const FACEBOOK_GRAPH_DATA_REQUESTED = 'FACEBOOK_GRAPH_DATA_REQUESTED'
export const FACEBOOK_GRAPH_DATA_SUCCEEDED = 'FACEBOOK_GRAPH_DATA_SUCCEEDED'
export const FACEBOOK_GRAPH_DATA_FAILED    = 'FACEBOOK_GRAPH_DATA_FAILED'

export const SOCKET_CONNECTION_REQUESTED = 'SOCKET_CONNECTION_REQUESTED'
export const SOCKET_CONNECTION_SUCCEEDED = 'SOCKET_CONNECTION_SUCCEEDED'
export const SOCKET_CONNECTION_FAILED    = 'SOCKET_CONNECTION_FAILED'

export const SOCKET_LOGIN_USER_REQUESTED = 'SOCKET_LOGIN_USER_REQUESTED'
export const SOCKET_QUERY_USER_REQUESTED = 'SOCKET_QUERY_USER_REQUESTED'
export const SOCKET_QUERY_USER_RECEIVED  = 'SOCKET_QUERY_USER_RECEIVED'

export const SOCKET_QUERY_UNKNOWN_RECEIVED = 'SOCKET_QUERY_UNKNOWN_RECEIVED'